### ISSUE TITLE
Update token refresher image tag to the latest one

### ISSUE THREAD

**Issue by machi1990** [redhat-developer/observability-operator#184]
Once the new token refresher tag is there, we've to update https://github.com/redhat-developer/observability-operator/blob/c8fa615957b37e3cc48deec7d6c851de89255f71/controllers/reconcilers/configuration/token_refresher.go#L23 to point to the new tag and make a new Obs release. @vmanley @pb82 

@StevenTobin is looking onto getting the new image tag.

**Comment by vmanley** [comment]
Thanks @machi1990

**Comment by machi1990** [comment]
New image tag is there: https://quay.io/repository/rhoas/mk-token-refresher?tab=tags

**Comment by machi1990** [comment]
I'll open a PR on this one

**Comment by vmanley** [comment]
I have one ready now @machi1990

**Comment by machi1990** [comment]
Perfect! Thanks @vmanley
